/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package web_browser;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.*;
import java.util.ArrayList;
import javax.rmi.CORBA.Util;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Blogger
 */
public class Cookies extends javax.swing.JFrame {
    
    ArrayList<File> cookieFiles = new ArrayList<>();
    ArrayList<Connection> conn = new ArrayList<>();
    ArrayList<Statement> stmts = new ArrayList<>();
    ArrayList<ResultSet> rsa = new ArrayList<>();
            
    Utilities utilities = new Utilities();
    final ResultSetTableModel model = new ResultSetTableModel();
    JFrame parent = null;
    
    /**
     * Creates new form History
     */
    public Cookies() 
    {
        initComponents();
        jTable_Cookie.setShowGrid(true);
    }

    Cookies(JFrame frame) 
    {
        initComponents();
        jTable_Cookie.setShowGrid(true);
        parent = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Cookie = new javax.swing.JTable();
        button_ChromeCookies = new javax.swing.JButton();
        button_MozillaCookies = new javax.swing.JButton();
        exportExcel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        comboSelectUser = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Cookies");
        setName("View History"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable_Cookie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Cookie.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTable_Cookie);

        button_ChromeCookies.setText("Load Google Chrome History");
        button_ChromeCookies.setActionCommand("Load Google Chrome Cookies");
        button_ChromeCookies.setLabel("Load Google Chrome Cookies");
        button_ChromeCookies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ChromeCookiesActionPerformed(evt);
            }
        });

        button_MozillaCookies.setActionCommand("Load Mozilla Firefox Cookies");
        button_MozillaCookies.setLabel("Load Mozilla Firefox Cookies");
        button_MozillaCookies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MozillaCookiesActionPerformed(evt);
            }
        });

        exportExcel.setLabel("Export to Excel");
        exportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportExcelActionPerformed(evt);
            }
        });

        jLabel1.setText("Select User:");

        String userDirectory = System.getProperty("user.home");
        File root = new File("C:\\Users\\");
            File[] list = root.listFiles();

            for ( File f : list )
            {
                if ( f.isDirectory() )
                {
                    comboSelectUser.addItem(f.getName());
                }
            }

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(exportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(comboSelectUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(button_ChromeCookies, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(button_MozillaCookies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18))))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(button_ChromeCookies, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)
                            .addComponent(button_MozillaCookies, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(comboSelectUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(exportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void button_ChromeCookiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ChromeCookiesActionPerformed
        try
        {
            cookieFiles = utilities.getChromeFiles("C:\\Users\\"+comboSelectUser.getSelectedItem()+"\\AppData\\Local\\Google\\Chrome\\User Data", "Cookies");
            
            if(cookieFiles.size() >= 1)
            {
                for (int i=0; i<cookieFiles.size();i++)
                {
                    conn.add(i,DbController.getConnection(cookieFiles.get(i).toString()));
                    stmts.add(conn.get(i).createStatement());

                    rsa.add( stmts.get(i).executeQuery("SELECT host_key as Host,name as 'Cookie name',value as 'Cookie Value',"
                    + "datetime((creation_utc / 1000000) + (strftime('%s', '1601-01-01')), 'unixepoch','localtime') as 'Creation Date',"
                    + "datetime((last_access_utc / 1000000) + (strftime('%s', '1601-01-01')), 'unixepoch','localtime') as 'Last Accessed Date',"
                    + "datetime((expires_utc / 1000000) + (strftime('%s', '1601-01-01')), 'unixepoch','localtime') as 'Expiration Date' "
                    + "FROM cookies;"));
                }
                model.setResultSet(rsa);
                System.out.println ("Row Count : " + model.getRowCount());
                jTable_Cookie.setModel(model);
                jTable_Cookie.setAutoCreateRowSorter(true);
            }
            else
            {
                JOptionPane.showMessageDialog(jTable_Cookie, "No Cookies found on this system");
            }
        }
        catch (Exception ex)
        {
            if (ex.getMessage().contains("The database file is locked"))
            {
                JOptionPane.showMessageDialog(jTable_Cookie, "Please Close google chrome and try again in 30 seconds");
            }
            else
            {
                System.out.println("Catch Error in button_ChromeCookiesActionPerformed: " + ex.getMessage());
            }
        }
        finally
        {
            try 
            {
                cookieFiles.clear(); conn.clear(); stmts.clear();rsa.clear();   
            } 
            catch (Exception ex) 
            {
               System.out.println("Finally Error in button_ChromeCookiesActionPerformed: " + ex.getMessage() );
            }
        }
    }//GEN-LAST:event_button_ChromeCookiesActionPerformed

    private void button_MozillaCookiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MozillaCookiesActionPerformed
        try
        {
            cookieFiles = utilities.getMozillaFiles("C:\\Users\\"+comboSelectUser.getSelectedItem()+"\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles","cookies.sqlite");
            
            if(cookieFiles.size() >= 1)
            {
                for (int i=0; i<cookieFiles.size();i++)
                {
                    conn.add(i,DbController.getConnection(cookieFiles.get(i).toString()));
                    stmts.add(conn.get(i).createStatement());
                    rsa.add(stmts.get(i).executeQuery("SELECT baseDomain as Host,name as 'Cookie name',value as 'Cookie Value',"
                    + "datetime((creationTime / 1000000), 'unixepoch','localtime') as 'Creation Date',"
                    + "datetime((lastAccessed / 1000000), 'unixepoch','localtime') as 'Last Accessed Date',"
                    + "datetime((expiry) , 'unixepoch','localtime') as 'Expiration Date' "
                    + "FROM moz_cookies;"));
                }
                model.setResultSet(rsa);
                System.out.println ("Row Count : " + model.getRowCount());
                jTable_Cookie.setModel(model);
                jTable_Cookie.setAutoCreateRowSorter(true);
            }
            else
            {
                JOptionPane.showMessageDialog(jTable_Cookie, "No Cookies found on this system");
            }
        }
        catch (Exception ex)
        {
            System.out.println("Catch Error in button_MozillaCookiesActionPerformed: " + ex.getMessage());
        }
        finally
        {
            try 
            {
                cookieFiles.clear(); conn.clear(); stmts.clear();rsa.clear();
            } 
            catch (Exception ex) 
            {
               System.out.println("Finally Error in button_MozillaHostActionPerformed: " + ex.getMessage() );
            }
        }
    }//GEN-LAST:event_button_MozillaCookiesActionPerformed

    private void exportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportExcelActionPerformed
        utilities.toExcel(jTable_Cookie, this);
    }//GEN-LAST:event_exportExcelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cookies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cookies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cookies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cookies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

       
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Cookies hosts = new Cookies();
                Utilities.setFrameLocation(hosts);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ChromeCookies;
    private javax.swing.JButton button_MozillaCookies;
    private javax.swing.JComboBox comboSelectUser;
    private javax.swing.JButton exportExcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Cookie;
    // End of variables declaration//GEN-END:variables
}
