/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package web_browser;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author Blogger
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button_Downloads = new javax.swing.JButton();
        button_Keywords = new javax.swing.JButton();
        button_History = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        button_Hosts = new javax.swing.JButton();
        button_Cookies = new javax.swing.JButton();
        mainMenu = new javax.swing.JMenuBar();
        menu_History = new javax.swing.JMenu();
        menu_Keywords = new javax.swing.JMenu();
        menu_Downloads = new javax.swing.JMenu();
        menu_Host = new javax.swing.JMenu();
        menu_Cookies = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Web Browser Forensics");
        setPreferredSize(new java.awt.Dimension(1100, 600));

        button_Downloads.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/downloads.png"))); // NOI18N
        button_Downloads.setText("Downloads");
        button_Downloads.setToolTipText("");
        button_Downloads.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_Downloads.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_Downloads.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_DownloadsMouseClicked(evt);
            }
        });

        button_Keywords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keywords.jpg"))); // NOI18N
        button_Keywords.setText("Keywords");
        button_Keywords.setToolTipText("");
        button_Keywords.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_Keywords.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_Keywords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_KeywordsMouseClicked(evt);
            }
        });

        button_History.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/history.png"))); // NOI18N
        button_History.setText("History");
        button_History.setToolTipText("");
        button_History.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_History.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_History.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_HistoryMouseClicked(evt);
            }
        });
        button_History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_HistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(button_History)
                .addGap(84, 84, 84)
                .addComponent(button_Keywords)
                .addGap(82, 82, 82)
                .addComponent(button_Downloads)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_Downloads, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_History, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_Keywords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        button_Hosts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hosts.png"))); // NOI18N
        button_Hosts.setText("Hosts");
        button_Hosts.setToolTipText("");
        button_Hosts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_Hosts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_Hosts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_HostsMouseClicked(evt);
            }
        });

        button_Cookies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cookies.jpg"))); // NOI18N
        button_Cookies.setText("Cookies");
        button_Cookies.setToolTipText("");
        button_Cookies.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_Cookies.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        button_Cookies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_CookiesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(button_Hosts)
                .addGap(87, 87, 87)
                .addComponent(button_Cookies)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_Cookies)
                    .addComponent(button_Hosts))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu_History.setText("History");
        menu_History.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_HistoryMouseClicked(evt);
            }
        });
        mainMenu.add(menu_History);

        menu_Keywords.setText("Keywords");
        menu_Keywords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_KeywordsMouseClicked(evt);
            }
        });
        mainMenu.add(menu_Keywords);

        menu_Downloads.setText("Downloads");
        menu_Downloads.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_DownloadsMouseClicked(evt);
            }
        });
        mainMenu.add(menu_Downloads);

        menu_Host.setText("Hosts");
        menu_Host.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_HostMouseClicked(evt);
            }
        });
        mainMenu.add(menu_Host);

        menu_Cookies.setText("Cookies");
        menu_Cookies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_CookiesMouseClicked(evt);
            }
        });
        mainMenu.add(menu_Cookies);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void menu_HistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_HistoryMouseClicked
       this.setVisible(false);
       History h = new History(this);
       h.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       Utilities.setFrameLocation(h);  
    }//GEN-LAST:event_menu_HistoryMouseClicked

    private void menu_HostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_HostMouseClicked
       this.setVisible(false);
       Hosts ho = new Hosts(this);
       ho.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       Utilities.setFrameLocation(ho);  
    }//GEN-LAST:event_menu_HostMouseClicked

    private void menu_CookiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_CookiesMouseClicked
       this.setVisible(false);
       Cookies coo = new Cookies(this);
       coo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       Utilities.setFrameLocation(coo);  
    }//GEN-LAST:event_menu_CookiesMouseClicked

    private void menu_DownloadsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_DownloadsMouseClicked
       this.setVisible(false);
       Downloads download = new Downloads(this);
       download.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       Utilities.setFrameLocation(download); 
    }//GEN-LAST:event_menu_DownloadsMouseClicked

    private void menu_KeywordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_KeywordsMouseClicked
       this.setVisible(false);
       Keywords keywords = new Keywords(this);
       keywords.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       Utilities.setFrameLocation(keywords); 
    }//GEN-LAST:event_menu_KeywordsMouseClicked

    private void button_HistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_HistoryMouseClicked
       this.setVisible(false);
       History h = new History(this);
       h.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       Utilities.setFrameLocation(h); 
    }//GEN-LAST:event_button_HistoryMouseClicked

    private void button_KeywordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_KeywordsMouseClicked
       this.setVisible(false);
       Keywords keywords = new Keywords(this);
       keywords.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       Utilities.setFrameLocation(keywords); 
    }//GEN-LAST:event_button_KeywordsMouseClicked

    private void button_DownloadsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DownloadsMouseClicked
       this.setVisible(false);
       Downloads download = new Downloads(this);
       download.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       Utilities.setFrameLocation(download); 
    }//GEN-LAST:event_button_DownloadsMouseClicked

    private void button_HostsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_HostsMouseClicked
       this.setVisible(false);
       Hosts ho = new Hosts(this);
       ho.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       Utilities.setFrameLocation(ho);  
    }//GEN-LAST:event_button_HostsMouseClicked

    private void button_CookiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_CookiesMouseClicked
       this.setVisible(false);
       Cookies coo = new Cookies(this);
       coo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       Utilities.setFrameLocation(coo);  
    }//GEN-LAST:event_button_CookiesMouseClicked

    private void button_HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_HistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_HistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                Main m = new Main();
                Utilities.setFrameLocation(m);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Cookies;
    private javax.swing.JButton button_Downloads;
    private javax.swing.JButton button_History;
    private javax.swing.JButton button_Hosts;
    private javax.swing.JButton button_Keywords;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenu menu_Cookies;
    private javax.swing.JMenu menu_Downloads;
    private javax.swing.JMenu menu_History;
    private javax.swing.JMenu menu_Host;
    private javax.swing.JMenu menu_Keywords;
    // End of variables declaration//GEN-END:variables
}
